name: innoverse
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  # color: "#BDE1FF"
  # color_dark: "#042a49"
  background_image: "assets/icon/splash.jpg"
  # fullscreen: true
  android_gravity: fill_vertical

  # dart run flutter_native_splash:create

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  font_awesome_flutter: ^10.5.0
  firebase_auth: ^4.6.3
  uuid: ^3.0.7
  flutter_staggered_grid_view: ^0.6.2
  slide_drawer: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
